export const ROUTES = {
  HOME: '/',
  DOCTORS: '/doctors',
  DOCTOR_DETAIL: '/doctors/:id',
  HOSPITALS: '/hospitals',
  HOSPITAL_DETAIL: '/hospitals/:id',
  SPECIALITIES: '/specialities',
  SPECIALIST: '/specialist',
  SPECIALISTS: '/specialists',
  SPECIALITY_DETAIL: '/specialities/:id',
  SPECIALIST_DETAIL: '/specialist/:id',
  APPOINTMENT: '/book-appointment',
  BLOG: '/blog',
  PROFILE: '/profile',
  PATIENT_REVIEW: '/patient-review',
  LOGIN: '/login',
  REGISTER: '/register',
  NOT_FOUND: '*',
};